package context

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// EnvEntry represents a key-value pair for .env file
type EnvEntry struct {
	Key   string
	Value string
}

// WriteEnvFile creates or updates an .env file with the provided entries
func WriteEnvFile(rootDir string, filename string, entries []EnvEntry) error {
	path := filepath.Join(rootDir, filename)

	// Prepare content
	var content strings.Builder
	content.WriteString("# Generated by Yby CLI\n")

	for _, entry := range entries {
		// Basic escaping for value if needed, but for now simple string
		content.WriteString(fmt.Sprintf("%s=%s\n", entry.Key, entry.Value))
	}

	// Write file with restricted permissions (since it might contain secrets)
	return os.WriteFile(path, []byte(content.String()), 0600)
}
