package context

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWriteEnvFile_Basic(t *testing.T) {
	tmpDir := t.TempDir()

	entries := []EnvEntry{
		{Key: "DB_HOST", Value: "localhost"},
		{Key: "DB_PORT", Value: "5432"},
		{Key: "APP_ENV", Value: "development"},
	}

	err := WriteEnvFile(tmpDir, ".env", entries)
	if err != nil {
		t.Fatalf("WriteEnvFile failed: %v", err)
	}

	// Verify file was created
	p := filepath.Join(tmpDir, ".env")
	data, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("failed to read .env file: %v", err)
	}

	content := string(data)

	// Check header comment
	if !strings.Contains(content, "# Generated by Yby CLI") {
		t.Error("expected header comment in .env file")
	}

	// Check entries
	if !strings.Contains(content, "DB_HOST=localhost") {
		t.Error("expected DB_HOST=localhost in .env file")
	}
	if !strings.Contains(content, "DB_PORT=5432") {
		t.Error("expected DB_PORT=5432 in .env file")
	}
	if !strings.Contains(content, "APP_ENV=development") {
		t.Error("expected APP_ENV=development in .env file")
	}
}

func TestWriteEnvFile_EmptyEntries(t *testing.T) {
	tmpDir := t.TempDir()

	err := WriteEnvFile(tmpDir, ".env.test", []EnvEntry{})
	if err != nil {
		t.Fatalf("WriteEnvFile with no entries failed: %v", err)
	}

	p := filepath.Join(tmpDir, ".env.test")
	data, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("failed to read file: %v", err)
	}

	if !strings.Contains(string(data), "# Generated by Yby CLI") {
		t.Error("expected at least header comment in empty .env file")
	}
}

func TestWriteEnvFile_OverwritesExisting(t *testing.T) {
	tmpDir := t.TempDir()
	p := filepath.Join(tmpDir, ".env")

	// Write initial content
	os.WriteFile(p, []byte("OLD_VAR=old_value\n"), 0600)

	entries := []EnvEntry{
		{Key: "NEW_VAR", Value: "new_value"},
	}
	err := WriteEnvFile(tmpDir, ".env", entries)
	if err != nil {
		t.Fatalf("WriteEnvFile overwrite failed: %v", err)
	}

	data, _ := os.ReadFile(p)
	content := string(data)

	if strings.Contains(content, "OLD_VAR") {
		t.Error("expected old content to be overwritten")
	}
	if !strings.Contains(content, "NEW_VAR=new_value") {
		t.Error("expected new content in file")
	}
}

func TestWriteEnvFile_FilePermissions(t *testing.T) {
	tmpDir := t.TempDir()

	err := WriteEnvFile(tmpDir, ".env", []EnvEntry{{Key: "SECRET", Value: "supersecret"}})
	if err != nil {
		t.Fatalf("WriteEnvFile failed: %v", err)
	}

	p := filepath.Join(tmpDir, ".env")
	info, err := os.Stat(p)
	if err != nil {
		t.Fatalf("failed to stat .env file: %v", err)
	}

	// File should have restricted permissions (0600)
	mode := info.Mode()
	if mode.Perm() != 0600 {
		t.Errorf("expected file permissions 0600, got %v", mode.Perm())
	}
}

func TestWriteEnvFile_InvalidDir(t *testing.T) {
	err := WriteEnvFile("/nonexistent/path/xyz", ".env", []EnvEntry{{Key: "K", Value: "V"}})
	if err == nil {
		t.Error("expected error writing to nonexistent dir, got nil")
	}
}
