# Documentação: https://golangci-lint.run/usage/configuration/
run:
  # O timeout está configurado para 5m para evitar falhas no CI
  timeout: 5m
  # Limitar concorrência para evitar OOM em runners com pouco recurso
  concurrency: 2

linters:
  # Desabilitar todos e habilitar apenas os essenciais
  disable-all: true
  enable:
    - gofmt
    - govet
    - ineffassign
    - staticcheck
    # - unused # Desabilitado por consumo excessivo de memória
    - revive

issues:
  # Restaurar padrões de exclusão úteis
  exclude-use-default: true
  # Excluir diretórios de terceiros e testes
  exclude-dirs:
    - vendor
    - testdata
    - plugins/sentinel/cli
    - test

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true # Ignorar stutter e comentários ausentes por enquanto para não quebrar CI
