version: 2
project_name: yby
before:
  hooks:
    - go mod tidy
builds:
  - id: core
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/yby
    binary: yby
    ldflags:
      - -s -w
      - -X github.com/casheiro/yby-cli/cmd.Version={{.Version}}
      - -X github.com/casheiro/yby-cli/cmd.commit={{.Commit}}
      - -X github.com/casheiro/yby-cli/cmd.date={{.Date}}
  - id: atlas
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./plugins/atlas
    binary: yby-plugin-atlas
    ldflags:
      - -s -w
  - id: bard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./plugins/bard
    binary: yby-plugin-bard
    ldflags:
      - -s -w
  - id: sentinel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./plugins/sentinel/cli
    binary: yby-plugin-sentinel
    ldflags:
      - -s -w
  - id: forge
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./plugins/forge
    binary: yby-plugin-forge
    ldflags:
      - -s -w
  - id: oracle
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./plugins/oracle
    binary: yby-plugin-oracle
    ldflags:
      - -s -w
  - id: viz
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./plugins/viz
    binary: yby-plugin-viz
    ldflags:
      - -s -w
archives:
  - id: core
    ids:
      - core
    formats: ["tar.gz"]
    # use zip for windows
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: atlas
    ids:
      - atlas
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: "yby-plugin-atlas_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: bard
    ids:
      - bard
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: "yby-plugin-bard_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: sentinel
    ids:
      - sentinel
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: "yby-plugin-sentinel_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: forge
    ids:
      - forge
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: "yby-plugin-forge_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: oracle
    ids:
      - oracle
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: "yby-plugin-oracle_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: viz
    ids:
      - viz
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]
    name_template: "yby-plugin-viz_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat((\\([\\w\\-\\.]+\\))?|!)?:"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix((\\([\\w\\-\\.]+\\))?|!)?:"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^typo:"
