version: 2
project_name: yby
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/yby
    ldflags:
      - -s -w
      - -X github.com/casheiro/yby-cli/cmd.version={{.Version}}
      - -X github.com/casheiro/yby-cli/cmd.commit={{.Commit}}
      - -X github.com/casheiro/yby-cli/cmd.date={{.Date}}
archives:
  - formats: ["tar.gz"]
    # use zip for windows
    format_overrides:
      - goos: windows
        formats: ["zip"]
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat((\\([\\w\\-\\.]+\\))?|!)?:"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix((\\([\\w\\-\\.]+\\))?|!)?:"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^typo:"
