version: "3"

tasks:
  default:
    cmds:
      - task: build

  setup-hooks:
    desc: Configure git hooks
    cmds:
      - git config core.hooksPath .githooks
      - chmod +x .githooks/pre-commit
      - echo "✅ Git hooks configured!"

  build:
    desc: Build all binaries
    cmds:
      - go build -o bin/yby ./cmd/yby
      - go build -o bin/yby-plugin-atlas ./plugins/atlas
      - go build -o bin/yby-plugin-bard ./plugins/bard
      - go build -tags k8s -o bin/yby-plugin-sentinel ./plugins/sentinel/cli
      - go build -tags k8s -o bin/yby-plugin-sentinel-agent ./plugins/sentinel/agent
      - go build -C ./plugins/synapstor -o ../../bin/yby-plugin-synapstor .
      - go build -C ./plugins/viz -o ../../bin/yby-plugin-viz .

  test:
    desc: Run tests
    cmds:
      - go test ./pkg/... ./plugins/...

  clean:
    desc: Clean bin directory
    cmds:
      - rm -rf bin/
