apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ingress.tls.issuer }}
spec:
  {{- if eq .Values.ingress.tls.issuer "custom" }}
  ca:
    secretName: {{ .Values.ingress.tls.caSecretName | default "enterprise-ca-secret" }}
  {{- else }}
  acme:
    # Email address used for ACME registration
    email: {{ .Values.ingress.tls.email }}
    {{- if eq .Values.ingress.tls.issuer "letsencrypt-prod" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    privateKeySecretRef:
      name: {{ .Values.ingress.tls.issuer }}
    solvers:
    {{- if eq .Values.ingress.tls.acmeSolver "dns01" }}
    - dns01: {}
    {{- else }}
    - http01:
        ingress:
          class: {{ .Values.ingress.className | default "traefik" }}
    {{- end }}
  {{- end }}
