package ai

import "context"

// UsageMetadata contém informações de uso de tokens de uma operação de IA.
type UsageMetadata struct {
	PromptTokens     int
	CompletionTokens int
	TotalTokens      int
	Provider         string
	Model            string
	Operation        string // "completion", "streaming", "embedding", "governance"
}

type usageKey struct{}

// SetUsage armazena metadados de uso no contexto.
func SetUsage(ctx context.Context, usage *UsageMetadata) context.Context {
	return context.WithValue(ctx, usageKey{}, usage)
}

// GetUsage recupera metadados de uso do contexto.
func GetUsage(ctx context.Context) *UsageMetadata {
	if v, ok := ctx.Value(usageKey{}).(*UsageMetadata); ok {
		return v
	}
	return nil
}

// GeneratedFile represents a file content generated by the AI
type GeneratedFile struct {
	Path    string `json:"path"`    // Relative path, e.g., ".synapstor/UKI_PCI.md"
	Content string `json:"content"` // validation: markdown content
}

// GovernanceBlueprint is the JSON structure we expect from the LLM
type GovernanceBlueprint struct {
	Domain    string          `json:"domain"`
	RiskLevel string          `json:"risk_level"`
	Summary   string          `json:"summary"`
	Files     []GeneratedFile `json:"files"`
}
