package ai

// GeneratedFile represents a file content generated by the AI
type GeneratedFile struct {
	Path    string `json:"path"`    // Relative path, e.g., ".synapstor/UKI_PCI.md"
	Content string `json:"content"` // validation: markdown content
}

// GovernanceBlueprint is the JSON structure we expect from the LLM
type GovernanceBlueprint struct {
	Domain    string          `json:"domain"`
	RiskLevel string          `json:"risk_level"`
	Summary   string          `json:"summary"`
	Files     []GeneratedFile `json:"files"`
}
