cert-manager:
  enabled: true
  installCRDs: true



argo-cd:
  configs:
    params:
      server.insecure: true

k3s:
  version: v1.33.6+k3s1
  upgrade:
    enabled: true # Habilitar apenas quando quiser atualizar via GitOps
